 jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Test and create report"
        run: |-
            Unity.exe -projectPath . -batchmode -testPlatform editmode -runTests -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./CodeCoverage -coverageOptions enableCyclomaticComplexity;assemblyFilters:-UnityEditor*;pathFilters:-*Packages* &&
            Unity.exe -projectPath . -batchmode -testPlatform playmode -runTests -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./CodeCoverage -coverageOptions enableCyclomaticComplexity;assemblyFilters:-UnityEditor*;pathFilters:-*Packages* &&
            Unity.exe -projectPath . -batchmode -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./CodeCoverage -coverageOptions generateHtmlReport;generateBadgeReport -quit
 name: "Generate report"
 on: workflow_dispatch
